spring:
  jpa:
    show-sql: ${SHOW_SQL}
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        dialect: ${DIALECT}
        jdbc:
          lob:
            non_contextual_creation: ${CONTEXTUAL_CREATION}
  datasource:
    username: ${USERNAME}
    password: ${PASSWORD}
    url: ${CONNECTION_STRING}
    driverClassName: ${DRIVER}
